apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    storage: slow
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: giropops
  hostPath:
    path: /mnt/data 