apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react-app
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: juanozorio/react-app
        resources:
          requests:
            memory: "256Mi"
            cpu: "1"
          limits:
            memory: "512Mi"
            cpu: "2"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /ui/
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /ui/
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1