apiVersion: v1
kind: Pod
metadata:
  name: girus
  labels:
    run: girus
spec:
  containers:
  - name: girus
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "0.2"
      limits:
        memory: "128Mi"
        cpu: "0.5"
    ports:
      - containerPort: 80
